apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::381702619623:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::381702619623:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-13SXMLI7GMNNW
      username: system:node:{{EC2PrivateDNSName}} 
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-04T14:06:10Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1574"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 12a512aa-32cc-4e25-8bd1-52acd6bd1ea5
