apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::381702619623:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::381702619623:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-8B3UBBYSOKQ5
      username: system:node:{{EC2PrivateDNSName}} 
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-03T15:07:44Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1590"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 42ac64d8-14d9-4125-a77a-be7563a25477