apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::381702619623:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-V0RLITEB4ILB
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::$381702619623:role/UdacityFlaskDeployCBKubectlRole
      username: perfect
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-23T11:04:54Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1677"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: dabba624-c722-4ad3-8de3-07ea1ff3c65c